### ISSUE TITLE
PreRelease ToDo: Fancy Language

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/mortAAR#23] opened 2017-06-24 14:16 UTC
Improve and harmonize language in documentation and vignettes.

**Comment by ctietze91** [comment] 2017-07-15 16:54
I'm going to hold back on any corrections until the problem with the check on my computer is fixed.
Franziska already tried to fix it, but it seems to be a much more complex problem than we thought.
Anyways, we fixed the problem I caused by not chaning the test versions wording too, so in the meantime there shouldn't be any problems with the package caused by me.

**Comment by nevrome** [comment] 2017-07-15 17:04
Did you install the [Rtools](https://cran.rstudio.com/bin/windows/Rtools/) for Windows?

**Comment by ctietze91** [comment] 2017-07-16 13:36
solved the problem. :)

**Comment by MartinHinz** [comment] 2017-07-18 11:54
:+1:

**Comment by ctietze91** [comment] 2017-07-25 16:21
So now I've got another problem while building and reloading (lazy loading error). 

But I still have some questions which would need some answers, so I can finish up the corrections and proceed to the extended vignette:

input function: (not sure who is in this group)
-l. 140 >what does "and all" mean? It would need to be specified.
-l. 130/156/166 >you chose the wording "male, female, whatever ..." or "... or whatever"
                         >>in the output function you chose "male, felmale, undetermined, ..."
I would try to get a uniform wording and scratch the whatever, since it seems kind of non-scientific, what do you say?

output function : @MartinHinz @quassinja 
-l. 20   >what exactly is "pretty printing"? Is it just pretty, cute, nice? if so, then i'd like to change it.
-l. 98   >what does "utils" mean? Does it actually mean "utilises"?
-l. 144/209  >it plots to show what exactly?

**Comment by nmueller18** [comment] 2017-07-25 16:54
-|. 140: "All" means all individuals, irrespective of grouping. Change it to "All" (with inverted commas), to make this clear.
-|. 130 etc.: The groupings are up to the user. In most cases, it will indeed be male, female, undetermined, but not in all. To restrain it to those case would also not reflect the possibilities correctly. While I agree that "whatever" is quite casual, it captures the intention. However, an alternative would be good.

**Comment by ctietze91** [comment] 2017-07-25 17:27
@nmueller18 : we could also keep the "whatever" and just add it to the output function.
In any case, it would be good to have a uniform picture, whichever version we agree on.

**Comment by MartinHinz** [comment] 2017-07-26 13:13
@ctietze91, thank you very much!

-l. 20: that is a common phrase for all format functions, consult eg. https://github.com/SurajGupta/r-source/blob/master/src/library/base/man/format.Rd line 14.
-l. 98: That is a call for a package of that exact name, please do not change this!
-l. 144/209: it shows plots, not it plots shows. So this param defines for which variables (eg. dx, qx, lx...) plots will be produced. So if you specify c("dx", "qx"), than dx and qx are plotted (against age). If not given, the parameter defaults to all. There might be a way to express this more clearly, open for suggestions!

Looking forward!

**Comment by ctietze91** [comment] 2017-07-28 13:10
I'm done with this issue. Moving on to the other one.
Maybe @nevrome  wants to close it?

**Closed as completed** 2017-07-28 13:12 UTC
